### ISSUE TITLE
Wagtail 6 Support

### ISSUE THREAD

**Issue by daveclarkit** [dinoperovic/django-salesman#38]
Are we going to get support for wagtail V6?

**Comment by dinoperovic** [comment]
@daveclarkit Yes, need to catch some free time to do the update.

Sorry I haven't seen you issue sooner :)

**Comment by GvozdevLeonid** [comment]
As I understand it you can release a quick update using wagtail-modeladmin

 https://github.com/wagtail-nest/wagtail-modeladmin
 
 I'm not sure how much of a long-term solution this is, but there are very few changes. Instead of importing 
 from wagtail.contrib.modeladmin... use from wagtail_modeladmin...

**Comment by dinoperovic** [comment]
@daveclarkit @GvozdevLeonid A release [1.2.1](https://github.com/dinoperovic/django-salesman/releases/tag/1.2.1) was made to support Wagtail 6.

This is to add support, but I am in process of migrating to using snippets in wagtail-6 instead of modeladmin.
